name: "Bug Report"
description: "Report a problem or issue with the website functionality"
title: "Bug: [Brief description of the problem]"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Found something that isn't working right? Please help us fix it by providing detailed information about the problem.
        
        **The more details you provide, the faster we can identify and fix the issue!**

  - type: textarea
    id: problem-description
    attributes:
      label: "What's Wrong?"
      description: "Describe the problem you're experiencing in simple terms"
      placeholder: "e.g., When I try to register a student for Chess Club, nothing happens when I click the Register button"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "How to Reproduce the Problem"
      description: "Tell us exactly what you did before the problem occurred. Be specific!"
      placeholder: |
        1. I logged in as a teacher
        2. I clicked on the Chess Club activity card
        3. I clicked the "Register Student" button
        4. I entered student@mergington.edu in the email field
        5. I clicked "Register"
        6. Nothing happened - no success message, no error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "What Should Happen Instead"
      description: "Describe what you expected to happen"
      placeholder: "e.g., The student should be added to the Chess Club participant list and I should see a success message"
    validations:
      required: true

  - type: dropdown
    id: bug-category
    attributes:
      label: "What Part of the Website Has the Problem?"
      description: "Help us narrow down where to look"
      options:
        - "Student registration/signup process"
        - "Teacher login process"
        - "Activity display/listing"
        - "Filtering and search"
        - "Visual appearance/styling"
        - "Mobile device usage"
        - "Page loading or performance"
        - "Other/Not sure"
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: "How Often Does This Happen?"
      options:
        - "Every time I try"
        - "Most of the time"
        - "Sometimes"
        - "Rarely"
        - "Just happened once"
    validations:
      required: true

  - type: checkboxes
    id: browser-device
    attributes:
      label: "What device/browser are you using?"
      description: "Check all that apply - this helps us test the same setup"
      options:
        - label: "Desktop computer"
        - label: "Laptop"
        - label: "Tablet (iPad, etc.)"
        - label: "Smartphone"
        - label: "Chrome browser"
        - label: "Firefox browser"
        - label: "Safari browser"
        - label: "Edge browser"
        - label: "Other browser"

  - type: dropdown
    id: user-type
    attributes:
      label: "Were you logged in when this happened?"
      options:
        - "Yes, logged in as a teacher"
        - "No, not logged in"
        - "I'm not sure"
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: "Any Error Messages?"
      description: "If you saw any error messages, pop-ups, or unusual text, write them here exactly as they appeared"
      placeholder: "e.g., 'Error 404: Activity not found' or 'Invalid teacher credentials'"

  - type: textarea
    id: additional-context
    attributes:
      label: "Anything Else We Should Know?"
      description: "Any other details that might help us understand and fix the problem"
      placeholder: "e.g., This started happening after the website was updated, or It only happens with certain student email addresses"

  - type: checkboxes
    id: impact-level
    attributes:
      label: "How much does this affect your work?"
      options:
        - label: "Blocks me from doing essential tasks"
        - label: "Makes things difficult but I can work around it"
        - label: "Minor inconvenience"

  - type: markdown
    attributes:
      value: |
        ---
        
        **For the coding assistant:** This is a bug report that needs investigation and fixing. Follow this approach:
        
        **Investigation steps:**
        1. Understand the exact steps that cause the problem
        2. Identify which part of the system is likely affected (frontend JS, backend API, database, or styling)
        3. Look for obvious issues in the relevant code files
        
        **Common areas to check:**
        - **JavaScript errors:** Check `src/static/app.js` for event handlers, API calls, and form processing
        - **Backend API issues:** Check `src/backend/routers/` for endpoint logic and error handling
        - **Database problems:** Check `src/backend/database.py` for data structure issues
        - **CSS/styling issues:** Check `src/static/styles.css` for display problems
        - **HTML structure:** Check `src/static/index.html` for form elements and IDs
        
        **Debugging approach:**
        1. Reproduce the issue if possible
        2. Check browser console for JavaScript errors
        3. Verify API endpoints return expected responses
        4. Test with different browsers/devices if relevant
        5. Make minimal changes to fix the root cause
        
        **Fix verification:**
        - Test the exact scenario described in "steps to reproduce"
        - Ensure the fix doesn't break other functionality
        - Consider edge cases mentioned in the bug report